services:
  news-summarizer-generative-model:
    image: espymur/summarization-generator:latest
    pull_policy: always
    tty: true
    env_file:
      - ../.env_prod
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.generator.schedule:  "0 00 23 05 * *"
      ofelia.job-exec.generator.command: "python src/llm/main.py -e prod --save_to_s3 1"
  
  ofelia_generator:
    image: mcuadros/ofelia:latest
    restart: "unless-stopped"
    depends_on:
      - news-summarizer-generative-model
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
