services:
  news-summarizer-generative-model:
    image: espymur/summarization-generator:latest
    pull_policy: always
    tty: true
    env_file:
      - ../.env_prod
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.generator.schedule:  "40 12 * * *"
      ofelia.job-exec.generator.command: "python src/llm/main.py -e prod --save_to_s3 1"
  news-summarizer-clustering:
    image: espymur/summarization-clustering:latest
    pull_policy: always
    tty: true
    volumes:
      - ${PWD}/models/dunzhang/stella_en_400M_v5:/app/models/dunzhang/stella_en_400M_v5
    env_file:
      - ../.env_prod
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.summarizer.schedule:  "20 12 * * *"
      ofelia.job-exec.summarizer.command: "python src/summarizer/main.py -e prod -d 1"
  ofelia:
    image: mcuadros/ofelia:latest
    restart: "unless-stopped"
    depends_on:
      - news-summarizer-generative-model
      - news-summarizer-clustering
    command: daemon --docker -f label=com.docker.compose.project=${COMPOSE_PROJECT_NAME}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
